### ISSUE TITLE
Using mdx string?

### ISSUE THREAD

**Issue by EarthlingDavey** [hashicorp/next-mdx-enhanced#50]
Hi, can I still use this package if I am making an api call and it returns the mdx as a string?

Is there a function in the package that I can use with this string?

For reference of what I'm trying to achieve, there is a rough equivalent for Gatsby here: https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/#make-a-template-for-your-posts

Thanks :)

**Comment by jescalan** [comment]
Oh hello, it's quite convenient that you'd ask this question, because I just finished writing a library that allows exactly this!

https://github.com/hashicorp/next-mdx-remote

Let me know what you think 💖

**Comment by EarthlingDavey** [comment]
Awesome timing!

 I'll take next-mdx-remote for a spin now. I wrote this for myself yesterday.

```
import React from 'react';
import MDX from '@mdx-js/runtime';

const components = {
  h1: (props) => <h1 style={{ color: 'tomato' }} {...props} />,
  img: (props) => <img {...props} src={gitLabImage(props.src)} />,
};
// Provide variables that might be referenced by JSX
const scope = {
  some: 'value',
};

export default (props) => (
  <MDX components={components} scope={scope}>
    {props.content}
  </MDX>
);
```

I'm fairly new to this, I'm also cautious about security because the mdx string will be user generated content.

Do you have time to make a quick comparison, and comment on security of next-mdx-remote?

**Comment by kylemac** [comment]
@EarthlingDavey using something `next-mdx-remote` will allow you to avoid having to ship the very large MDX runtime to your client-side bundles. 

https://mdxjs.com/advanced/runtime

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/49507/81085008-9bfced80-8ec4-11ea-9097-3f4a75f4f1fd.png">

**Comment by EarthlingDavey** [comment]
Ok, I understand some more now thanks. It sounds like I should be using next-mdx-remote then ;)
 
I've had a play around, unfortunately I hit a snag. ( https://github.com/hashicorp/next-mdx-remote/issues/2 )

I also have a couple of more questions but I've created them in an issue here: ( https://github.com/hashicorp/next-mdx-remote/issues/3 )

Thanks folks ✌️
