### ISSUE TITLE
Add support for `src` directory

### ISSUE THREAD

**Issue by jensmeindertsma** [hashicorp/next-mdx-enhanced#51]
Currently, when using a folder structure where `pages` is placed inside the `src` folder, this plugin fails to get the correct relative path and instead uses the entire path for `__resourcePath`. Since this file structure is a [feature supported by Next.js](https://nextjs.org/docs/advanced-features/src-directory), I believe support for this should be added.
**Example**
```
// When using `src` folder
import { frontMatter as blogPosts } from "./blog/*.mdx";
console.log(blogPosts.__resourcePath);
// Logs `:\\Coding\\jensmeindertsma\\src\\pages\\blog\\context.mdx`

// When `pages` is directly inside root
import { frontMatter as blogPosts } from "./blog/*.mdx";
console.log(blogPosts.__resourcePath);
// Logs `blog\context`
```

Is this related to `babel-plugin-import-glob-array`? I'm not sure. The page itself is still accessible when using the `src` folder approach, but the link to it inside `src/pages/blog.tsx` is not. This is when using the exact same component found in the documentation of this plugin:
```
import Link from 'next/link'
import { frontMatter as docsPages} from './blog/*.mdx'
export default () => {

  return (
    <>
      <h1>Docs Index</h1>
      <ul>
        {docsPages.map(page => (
          <li key={page.__resourcePath}>
            <Link href={formatPath(page.__resourcePath)}>
              <a>{page.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </>
  )
}

function formatPath(p) {
  return p.replace(/\.mdx$/, '')
}

**Comment by jescalan** [comment]
I would welcome a PR to add this feature if you're up for it! The way I'd propose fixing this would be to add an optional `root` option that can be passed to the plugin. You can see where the root-stripping logic is here:

https://github.com/hashicorp/next-mdx-enhanced/blob/master/index.js#L73
https://github.com/hashicorp/next-mdx-enhanced/blob/master/index.js#L109

**Comment by jensmeindertsma** [comment]
I'll have a look. Thanks for the help getting started!

**Comment by jensmeindertsma** [comment]
#52

**Comment by jensmeindertsma** [comment]
I've added a new prop `useSrc` that will add this to the path. How do I test if this works though?

**Comment by jensmeindertsma** [comment]
Could you please merge the PR when you have time?

**Comment by jescalan** [comment]
This has been merged and will be out shortly!
