### ISSUE TITLE
Next.js 9.4 breaking error

### ISSUE THREAD

**Issue by jensmeindertsma** [hashicorp/next-mdx-enhanced#53]
Hey 👋 @jescalan , I'm back with another problem that I encountered after upgrading to Next.js 9.4. I've managed to reproduce the issue [here](https://github.com/jensmeindertsma/issue-next-mdx-enhanced-2). This is really a basic setup, a `create-next-app` project where I've installed `next-mdx-enhanced` and `babel-plugin-import-glob-array`. This causes the following error: 
```
Attempted import error: 'frontMatter' is not exported from 'C:\dev\issue-next-mdx-enhanced-2\pages\blog\test.mdx' (imported as '_iga').
Could not find files for /blog in .next/build-manifest.json
```
After looking through the 9.4 changelog, I believe this is caused by the new React Refresh, although I'm not certain at all? It might be caused by the absolute path imports? 

This repository also contains branch `next-9.3` where I've downgraded to Next.js 9.3.6, and this works fine. 
Could you please investigate this? This prevents everyone from using Next.js 9.4.

**Comment by jensmeindertsma** [comment]
I believe this has a very high priority. After cloning the repository and running the tests, I discovered there is a change in Next.js 9.4 that causes `next-mdx-enhanced` to fail: it can't find `webpack` anymore. When I downgrade to 9.3.6 it works fine. I believe the problem is due to the new **`ReactRefreshWebpackPlugin`**

**Comment by peduarte** [comment]
Thanks for raising. Was just about to do the same.

**Comment by jensmeindertsma** [comment]
I've got no idea how to solve this though ¯\_(ツ)_/¯

**Comment by peduarte** [comment]
From Tim, [src](https://twitter.com/timneutkens/status/1260278581726449664):
> Potentially related to upgraded Babel dependencies Thinking face Guess a node  might have changed in the AST

**Comment by jescalan** [comment]
Aware of this issue. I will get to it as soon as I am able. In the meantime, the right move is to hold off on upgrading to next.js `9.4.0`

**Comment by jensmeindertsma** [comment]
I've got it boiled down to this snippet in the Babel plugin:
```js
// ...and insert it after the current import
          _path.insertAfter([frontMatterImport])

          // then we remove the front matter specifier from the current import
          if (_path.node.specifiers.length === 1) {
            // if its the only specifier, we remove the entire import
            _path.remove()
          } else {
            _path.node.specifiers = _path.node.specifiers.reduce((acc, s) => {
              // otherwise, we only remove the frontMatter import specifier
              if (!importsFrontMatter(s)) acc.push(s)
              return acc
            }, [])
          }
```
This code does not affect the AST somehow.
Directly modifying the exisiting node with 
```js
_path.node.source.value = frontMatterPath
```
does correctly modify the AST. I've tried replacing `_path.insertAfter` with `_path.replaceWith` but it had no effect either. Perhaps this can help you @jescalan with getting this fixed. Meanwhile, I'll continue investigating and I'll drop a PR once I find a fix.
