### ISSUE TITLE
Index file in subdirectory

### ISSUE THREAD

**Issue by drewes** [hashicorp/next-mdx-enhanced#58]
Thanks for an awesome library.

All the examples show the index file in the root of the `pages` directory.

I'm trying to set up a nested content library with subfolders in the docs. When I create a post index in a subdirectory, the `pages.__resourcePath` property returns the relative path from the root `pages` directory, and not relative to the index file location.

I'm a noob at this, and am just checking if this is the expected behaviour?

**Comment by jescalan** [comment]
This is indeed the expected behavior!
