### ISSUE TITLE
Rehype plugin not loading

### ISSUE THREAD

**Issue by geraldoramos** [hashicorp/next-mdx-enhanced#62]
I'm trying to install the  `rehype-autolink-headings` rehype plugin but nothing happens, it looks like the plugin is not being triggered.

Here is my next config:

```ts
const withMdxEnhanced = require('next-mdx-enhanced')
const withImages = require('next-images')

module.exports = withMdxEnhanced({
    layoutPath: 'components/common/Layout/',
    defaultLayout: false,
    fileExtensions: ['mdx'],
    remarkPlugins: [],
    rehypePlugins: [require("rehype-autolink-headings")],
    extendFrontMatter: {
        process: (mdxContent, frontMatter) => {},
        phase: 'prebuild|loader|both',
    },
})(withImages())
```

Am I missing anything? Is this a bug?

Thanks,

Geraldo

**Comment by estevanmaito** [comment]
Same problem and config, except I'm not using `next-images`.

**Comment by estevanmaito** [comment]
I figured it out.

`rehype-slug` is required for `rehype-autolink-headings` to work. It's not documented.

Install and add it to `rehypePlugins`:

```sh
npm i rehype-slug
```

```js
rehypePlugins: [require('rehype-slug'), require('rehype-autolink-headings')],
```
