### ISSUE TITLE
Using next/link for links inside markdown

### ISSUE THREAD

**Issue by crswll** [hashicorp/next-mdx-enhanced#83]
Is there a trick to getting `[about](/about)` to work without reloading as we navigate? I've done it before with a "wrapper" (https://mdxjs.com/guides/wrapper-customization) but not sure that's the preferred method with this plugin.

I imagine I'm missing something in the README that's obvious to someone wiser.

**Comment by jescalan** [comment]
You'd have to override `a` as a custom element with an implementation of `next/link`, using an `MDXProvider`. Something like this inside your layout. I am blind coding here so it may not be perfect but hopefully you get the gist!

```js
import Link from 'next/link'
import { MDXProvider } from '@mdx-js/mdx

const customLink = ({ href, children }) => <Link href={href}><a>{children}</a></Link>

return function Layout({ children }){
  return (
    <MDXProvider components={{ a: customLink }}>
      {children}
    </MDXProvider>
  )

}
```

**Comment by crswll** [comment]
It looks exactly like what I had before. I just wanted to make sure I wasn't overlooking anything. Thanks so much and I'll close this!
