### ISSUE TITLE
using frontMatter data inside of the getStaticProps function

### ISSUE THREAD

**Issue by eddiewang** [hashicorp/next-mdx-enhanced#86]
Hi there!

Thanks for making such a useful tool to use MDX with next.js.

I'm trying to figure out a way to pull a frontmatter variable from a parsed .mdx file into the getStaticProps function, in so that I can use that variable to load some data on build-time.

Haven't figured out an easy way to do this, due to variable scoping issues. I was wondering if there may be something I missed.

**Comment by jescalan** [comment]
He @eddiewang - you can do it with this library, but this is the type of task that [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote) was built for specifically.

To do it with this library, you just need to import the mdx file's front matter, then use it within `getStaticProps`, as such:

```jsx
import { frontMatter } from './path/to/your/file.mdx'

export async function getStaticProps() {
  console.log(frontMatter)
}
```

**Comment by eddiewang** [comment]
Thanks! mdx-remote did the job for me. Now to replace all the layouts with the new format :)
