### ISSUE TITLE
React 17 error, "pragma and pragmaFrag cannot be set when runtime is automatic."

### ISSUE THREAD

**Issue by NateRadebaugh** [hashicorp/next-mdx-enhanced#89]
When I navigate to the MDX pages, I get this error:
> pragma and pragmaFrag cannot be set when runtime is automatic.

Seeing on the latest version of `react@17` and `next@10`

**Comment by jose-donato** [comment]
I'm also getting the same error with the new react and next versions

**Comment by jescalan** [comment]
Seems like the new major versions have broken this plugin. I'll look into a resolution this week.

**Comment by NateRadebaugh** [comment]
The latest versions of `react@17` and `next@10` and `next-mdx-enhanced@5` are working for me now, thanks!!

**Comment by GenisDiaz** [comment]
Hello! I've updated the versions, even the next-mdx-enhanced, and for me, it still breaks. :( any idea?

**Comment by jescalan** [comment]
@GenisDiaz if you can provide a minimal reproduction of your issue I'd be happy to take a look!
