### ISSUE TITLE
How to convert img tags from MDX to use Next.js Image Component

### ISSUE THREAD

**Issue by geekysrm** [hashicorp/next-mdx-enhanced#92]
Hi,
Love this package.

[Next.js' Image component](https://nextjs.org/docs/basic-features/image-optimization) got released and I am trying to use it in my blog posts written as MDX files. I am using this package.

How do I change all the 'img' tags (in the markup generated from MDX) to 'Next.js's <Image />' tag?

**Comment by jescalan** [comment]
Add a mdx provider wrapping your pages and pass it as an image override!

https://mdxjs.com/getting-started/#mdxprovider

**Comment by geekysrm** [comment]
Thanks! That did the trick!
